source 'https://rubygems.org'
ruby '2.2.1'
gem 'rails', '4.2.5'

gem 'devise'
gem 'devise-bootstrap-views'
gem 'draper', '~> 1.3'
gem 'nokogiri'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem